/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.entities.User;
import ticket.booking.services.UserBookingService;
import ticket.booking.util.UserServiceUtil;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.UUID;

public class App {

    public static void main(String[] args) {
        System.out.println("Started");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try {
            userBookingService = new UserBookingService();
            System.out.println("Here");
        }catch (IOException e) {
            System.out.println("Error");
            return;
        }
        while(option != 7) {
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");
            option = scanner.nextInt();
            switch (option) {
                case 1:
                    System.out.println("Enter your username: ");
                    String usernameForSignUp = scanner.next();
                    System.out.println("Enter your password: ");
                    String passwordForSignUp = scanner.next();
                    User userSignUp = new User(usernameForSignUp, passwordForSignUp, UserServiceUtil.hashPassword(passwordForSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.userSignUp(userSignUp);
                    break;
                case 2:
                    System.out.println("Enter your username: ");
                    String usernameForLogIn = scanner.next();
                    System.out.println("Enter your password: ");
                    String passwordForLogIn = scanner.next();
                    User userLogIn = new User(usernameForLogIn, passwordForLogIn, UserServiceUtil.hashPassword(passwordForLogIn), new ArrayList<>(), UUID.randomUUID().toString());
                    try {
                        userBookingService = new UserBookingService(userLogIn);
                    }
                    catch (Exception e) {
                        return;
                    }
                    break;
                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("Enter source station");
                    String source = scanner.next();
                    System.out.println("Enter destination station");
                    String destination = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source, destination);
                    break;
                case 5:
                    break;
                case 6:
                    break;

                default:
                    System.out.println("Hii");
                    break;
            }
        }
    }
}
